name: mpd-ex
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - notebook
  - ipykernel
  - jupyter_client<8
  - pandas
  - geopandas
  - movingpandas
  - geoviews
  - hvplot
  - h3-py
  - stonesoup
